import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./_UIcomponents/Navbar";
import Footer from "./_UIcomponents/Footer";
import CustomCursor from "./_UIcomponents/CursorAnim";

const poppins = Poppins({ subsets: ["latin"] , weight: ["400", "500", "600", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        <CustomCursor />
        {children}
        <Footer />
      </body>
    </html>
  );
}
